### ISSUE TITLE
My repo is on your account for some reason?

### ISSUE THREAD

**Issue by Heath123** [misike12/misike12#2]
Hello, I had a repo https://github.com/Heath123/commit-in-past which I deleted, but now my activity still goes back to the 1970s but it says my contribution was to https://github.com/misike12/commit-in-past now. I'm trying to work out if this is a bug that didn't delete my repo properly, or whether you intentionally made a copy of my repo. If you didn't do this on purpose I think it would make sense to tell to GitHub as it could be a security flaw, if you did then that's fine but I'm trying to clean up the appearance of my profile a bit because I have to write a CV so it could be helpful if you could delete it so my contribution history doesn't look fake by going back to the 1970s.

**Comment by misike12** [comment]
Done.
![image](https://github.com/misike12/misike12/assets/59843249/4f741b47-1fbc-42c6-8315-d4221fa556f0)

**Comment by Heath123** [comment]
Thank you! For some reason it still shows the options for the old years on my profile, though hopefully it will update eventually
